version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest test_HW_04a_API.py
            source venv/bin/activate
            pytest --cov=your_project_folder

workflows:
  version: 2
  test_pipeline:
    jobs:
      - build
